apiVersion: v1
kind: Pod
metadata:
  name: net-debug
  namespace: default
  labels:
    app: net-debug
spec:
  containers:
    - name: net-debug
      image: nicolaka/netshoot:latest
      command: ["sleep", "infinity"]
  restartPolicy: Never
