apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: "pushgateway"
        static_configs:
          - targets:
              - "pushgateway:9091"

      - job_name: "loadgen"
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - eth
        relabel_configs:
          # Keep only Services with label app=loadgen
          - source_labels: [__meta_kubernetes_service_label_app]
            regex: loadgen
            action: keep

          # Keep only endpoints where the port name = metrics
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            regex: metrics
            action: keep

      - job_name: "grafana"
        static_configs:
          - targets:
              - "grafana:3000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image }}"
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.retention.time={{ .Values.prometheus.retention }}
          ports:
            - name: http
              containerPort: 9090
          volumeMounts:
            - name: cfg
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: cfg
          configMap:
            name: prom-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: http
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - pods
      - services
      - endpoints
      - namespaces
    verbs: ["get", "list", "watch"]

  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs: ["get", "list", "watch"]

  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: observability
