---
apiVersion: v1
kind: Service
metadata:
  # Stable service name for RPC endpoint: http://geth-dev:8545
  name: geth-dev
  labels: {{ - include "common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{ - include "common.selectorLabels" . | nindent 4 }}
  ports:
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: rpc
    - name: ws
      port: {{ .Values.service.wsPort }}
      targetPort: ws
